### ISSUE TITLE
COM Port  Issue...

### ISSUE THREAD

**Issue by DaddyWarhammer** [armel/M5HamRadio#3]
Project requires COM port to communicate with M5Stack. 
My Win7 computer has no COM ports. 
Is there a virtual Serial port driver that will work?

**Comment by armel** [comment]
Hi,

Like any other device, using an M5Stack with a PC (to flash or program it) requires the installation of a driver. This is explained in the documentation. Please take the time to read it carefully. That's why it's there. 

https://github.com/armel/M5HamRadio#usb-drivers-installation

Armel F4HWN.

**Comment by DaddyWarhammer** [comment]
Problem is, when I install the drivers, Windows Device Manager flags the entry and gives an error 52.
![image](https://user-images.githubusercontent.com/116251119/197063908-b75f0be5-1fa4-4210-a4c3-7be9dc481ba9.png)
After examining the certificate, it appears to be expired.
![image](https://user-images.githubusercontent.com/116251119/197064617-2c9e11a9-5fe3-4681-bf9b-b1c834a467c9.png)

**Comment by armel** [comment]
Ok, well, this is an operating system issue due to your Windows version and settings. This is not an issue about my projet. I don't work under Windows, but take a look at this link :

https://www.wintips.org/how-to-fix-windows-cannot-verify-the-digital-signature-for-this-file-error-in-windows-8-7-vista/

It explains how to bypass and disable the _Driver Signature Enforcement_. May be this tip works. Note that, Windows 7 support has been ended for almost 3 years. 

If this does not work, contact M5Stack. I can't help you install the M5Stack device. I don't develop drivers, just firmwares who work on M5Stack.

73'

Armel F4HWN.

**Comment by DaddyWarhammer** [comment]
OK, thanks - I'll try that.
I think, ultimately, I'll need to upgrade to a new laptop and use the newer universal driver M5Stack has on their site.

Anyway, I do appreciate your quick replies and I can't wait to get the code running!
Regards,
Paul.

**Comment by armel** [comment]
Ok Paul. 
I'm sure you'll fix this problem. Driver issues are always a pain to solve, i know 😔
Let me know if you have any other problem. I will try to do my best.

73'

Armel F4HWN.

**Comment by DaddyWarhammer** [comment]
Thank you, sir.
